# Generated by Django 4.0.4 on 2022-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_kind_pro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
