# Generated by Django 4.0.4 on 2022-06-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pro_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='kind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pro',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
