# Generated by Django 4.0.4 on 2022-06-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_pro_kind_alter_pro_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
