# Generated by Django 4.0.4 on 2022-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='image',
            field=models.ImageField(default='C:/Users/Lenovo/Desktop/desktop/djangotest0/base/images/smoothie.jpg', upload_to='images'),
        ),
    ]
