# Generated by Django 4.0.4 on 2022-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='image',
            field=models.ImageField(default='https://image.shutterstock.com/image-vector/collection-12-vector-ice-cream-600w-311740076.jpg', upload_to='images'),
        ),
    ]
